### ISSUE TITLE
Missing dependencies (orchestral/support) when installing through composer

### ISSUE THREAD

**Issue by disperun** [orchestral/asset#11]
There seems to be a missing dependency when installing orchestral/asset through composer.

If you adjust the composer.json like mentioned in the installation documentation it will install orchestral/asset without any errors but as soon as you add the Alias to config/app, the Facade couldn't be resolved. The package orchestral/support seems to be missing in the dependency tree. 

Workaround: adding orchestral/support manually to composer.json. Then everything can be resolved fine again.

**Comment by crynobone** [comment]
> Workaround: adding orchestral/support manually to composer.json. Then everything can be resolved fine again.

Sorry, this might be something we miss since moving from `orchestra/html` to `laravie/html`. Will push a fix soon.

**Comment by crynobone** [comment]
Fixes in f078a42
