### ISSUE TITLE
Can`t install version 3.4 - Composer minimum-stability

### ISSUE THREAD

**Issue by andersondalmina** [orchestral/asset#13]
Is not version 3.4 stable?

Composer error:
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Installation request for orchestra/asset ~3.4 -> satisfiable by orchestra/asset[v3.4.0].
    - orchestra/asset v3.4.0 requires orchestra/contracts ~3.4.0 -> satisfiable by orchestra/contracts[3.4.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by crynobone** [comment]
Should be fixed now.
