### ISSUE TITLE
Argument 2 passed to Orchestra\Asset\Asset::script() must be of the type string, null given

### ISSUE THREAD

**Issue by leenooks** [orchestral/asset#14]
Hi, I've tried using `@css` and `@js` with urls that just start with `//`, however, it generates the error above:

```Argument 2 passed to Orchestra\Asset\Asset::script() must be of the type string, null given```

I've hand a quick look at the code, and it seems that you are testing for http, https and // URLs but the error is thrown before it gets to isLocalPath()

I dont understand enough how these blade tags are being called to figure out where the problem might be - hoping you could provide some pointers.

So, using `@css('https://cdn/url')` works, but using `@css('//cdn/url')` throws the above error.

(I'm using v3.8.0.)

**Comment by crynobone** [comment]
1. this package doesn't introduce `@css()` or `@js()` directive.
2. If `@css('//cdn/url')` return `string` instead of `null`. The package should work. 

We can't control if `@css('//cdn/url')` return `null`.

**Comment by leenooks** [comment]
Can you help me where the @css/@js directives are introduced?
