### ISSUE TITLE
Blade @jsIn not working

### ISSUE THREAD

**Issue by pepoteloko** [orchestral/asset#15]
I'm not sure if it's a bug, but:

`@jsIn('footer', $dinamicUrl)` is not working but `Asset::container('footer')->add('url', $dinamicUrl);` is working fine.

**Comment by crynobone** [comment]
`orchestra/asset` doesn't provide `@jsIn()` blade directive.

**Comment by pepoteloko** [comment]
Sorry! I see it just right now.
Is from another package.
