### ISSUE TITLE
Asset dependency

### ISSUE THREAD

**Issue by kutukode** [orchestral/asset#8]
Hi,

I tried to use asset dependency like this, but it seems not working:
````
Asset::add('one', 'assets/js/one.js');

Asset::container('footer')
->add('two', 'assets/js/two.js', 'one');

// view
{{ Asset::container('footer')->scripts() }}
````
one.js isn't shown in the page, it shows only two.js. Did I miss something here?

PS. I'm on Laravel 4.2 and using orchestral/asset 2.2

Thanks!

**Comment by crynobone** [comment]
Because one.js is not within the same container as two.js

**Comment by kutukode** [comment]
Oh I see. I thought I can just declare some assets and use any of them as dependency anywhere including containers. 

Thanks.
